version: '3'
services:
  mydb:
    container_name: mydb
    image: mariadb
    env_file:
      - .env
    volumes:
      - /taller-docker/volumenes/mydb:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always

  mybackend:
    container_name: mybackend
    image: ingsistemascloud/mytomcat
    ports:
      - 8080:8080
    depends_on:
     - mydb
  
  myfrontend:
    container_name: myfrontend
    image: nginx    
    volumes:
      - /taller-docker/volumenes/myfrontend:/var/www/html
      - ./my-nginx.conf:/etc/nginx/conf.d/my-nginx.conf
    ports:
     - 80:80
    depends_on:
     - mybackend
